In [2]:
from numpy import matrix
from numpy.linalg import norm

def positions():
    position = matrix([[0], [0]])
    direction = matrix([[1], [0]])
    rotate = matrix([[0, 1], [-1, 0]])
    distance = 1
    while True:
        for times in range(2):
            for i in range(distance):
                yield position
                position += direction
            direction = rotate * direction
        distance += 1

special_addresses = (1, 12, 23, 1024, 347991)
a = 1
for p in positions():
    if a in special_addresses:
        print(a, norm(p, 1))
    a += 1
    if a > 347991:
        break

1 0.0
12 3.0
23 2.0
1024 31.0
347991 480.0


In [8]:
class memory:
    def __init__(self):
        self._values = {}
        
    def __setitem__(self, position, value):
        self._values[(position[0, 0], position[1, 0])] = value
    
    def __getitem__(self, position):
        return self._values.get((position[0, 0], position[1, 0]), 0)
    
    def sum_neighbours(self, position):
        neighbours = [
            matrix([[ 1], [ 0]]),
            matrix([[ 1], [ 1]]),
            matrix([[ 0], [ 1]]),
            matrix([[-1], [ 1]]),
            matrix([[-1], [ 0]]),
            matrix([[-1], [-1]]),
            matrix([[ 0], [-1]]),
            matrix([[ 1], [-1]]),
        ]
        return sum(self[position + d] for d in neighbours)

def memtest():
    position = matrix([[0], [0]])
    direction = matrix([[1], [0]])
    rotate = matrix([[0, 1], [-1, 0]])
    distance = 1
    values = memory()
    values[position] = 1
    while True:
        for times in range(2):
            for i in range(distance):
                position += direction
                value = values.sum_neighbours(position)
                yield value
                values[position] = value
            direction = rotate * direction
        distance += 1


In [11]:
for m in memtest():
    print(m)
    if m > 347991:
        break

1
2
4
5
10
11
23
25
26
54
57
59
122
133
142
147
304
330
351
362
747
806
880
931
957
1968
2105
2275
2391
2450
5022
5336
5733
6155
6444
6591
13486
14267
15252
16295
17008
17370
35487
37402
39835
42452
45220
47108
48065
98098
103128
109476
116247
123363
128204
130654
266330
279138
295229
312453
330785
349975
